documentation:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - '**/*.md'
      - all-globs-to-all-files:
        - '!src/**'
        - '!.github/**'
        - '!scripts/**'
        - '!.gitignore'
        - '!.pre-commit-config.yaml'

ci/cd:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - ".github/**"
        - "scripts/**"
        - ".gitignore"
        - ".pre-commit-config.yaml"
        - ".gitlab-ci.yml"
        - "alembic.ini"
      - all-globs-to-all-files:
        - '!./**/*.md'
        - '!src/**'

backend:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - "src/**"

tests:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - "tests/**"

docker:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - "deploy/**"
        - "!deploy/kube/**"
        - "Dockerfile"
        - "docker-compose.yml"

kubernetes:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - "deploy/kube/**"

dependencies:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - ''
      authors:
        - "dependabot[bot]"
