name: Lint with Pre-commit

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  gradle-code-quality:
    name: Gradle Code Quality
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [21, 25]

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"

      - name: Set up Python (for pre-commit)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        id: precommit
        run: |
          chmod +x ./gradlew
          pre-commit run --all-files --show-diff-on-failure --color always

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-jdk-${{ matrix.java-version }}
          path: |
            build/reports/
            **/build/reports/
